### ISSUE TITLE
Symlinks seem to be broken in test kitchen

### ISSUE THREAD

**Issue by karcaw** [biola/chef-zfs_linux#2]
when I try converging nodes almost immediatly i get errors such as:
       Transferring files to <default-ubuntu-1404>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [No such file or directory @ rb_file_s_stat - /tmp/default-ubuntu-1404-sandbox-20151104-61548-1k7ojtl/cookbooks/zfs_linux/test/integration/source]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

seems to be related to:
https://github.com/test-kitchen/test-kitchen/issues/503
https://github.com/test-kitchen/test-kitchen/issues/134

copying the directory in test/integration/default to source seems to solve the problem.

**Comment by troyready** [comment]
Thanks for the heads up!
